### ISSUE TITLE
better access for deploy

### ISSUE THREAD

**Issue by samsonasu** [tenforwardconsulting/subspace#28]
We should let the deploy user have view permissions to the webserver logs.  Maybe add a group or something? 

Deploy should also be able to restart apache if it can't already (but I think it can).  Anything else? Reboot the machine?

**Comment by boatrite** [comment]
I know deploy can access webserver logs. We added a thing to put them in the adm group which is what is needed for those log files.

They can also restart apache since they can sudo service.

They can't reboot, but I don't think that's needed.

Since there's nothing else really concrete in here, I'm going to close this. I think if there is a specific thing deploy should be able to do that they can't now, make a new issue.
